### PR TITLE
Optimize code

### PR DESCRIPTION
**Pull request by MrLivixx**
- added config with links
- Now, the socket is connected if the server is running. And it also reconnects when boticord restarts
- Some refractor code

**This code has not been tested. Check before merging**

### CODE REVIEW

**Comment by MrLivixx** [comment]
wtf, code is written in ts, and there is js
image

**Comment by XDENIX** [comment]
livixx privet

**Comment by san4ern** [comment]
> wtf, code is written in ts, and there is js
> image

library made for node.js projects, and yes, ts compiles in js, sure?

**Review by san4ern — CHANGES_REQUESTED** [review]
Please make required changes

**Pull request merged**
